version: '3'

services:
  judge0:
    image: judge0/judge0:1.13.0
    volumes:
      - ./judge0/judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    # Logging and restart settings if needed

  judge0-workers:
    image: judge0/judge0:1.13.0
    command: [ "./scripts/workers" ]
    volumes:
      - ./judge0/judge0.conf:/judge0.conf:ro
    privileged: true
    # Logging and restart settings if needed

  db:
    image: postgres:13.0
    env_file: ./judge0/judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    # Logging and restart settings if needed

  redis:
    image: redis:6.0
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
      ]
    env_file: ./judge0/judge0.conf
    volumes:
      - redis-data:/data
    # Logging and restart settings if needed

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
  postgres-data:
  redis-data:
